# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  database: hackathon_production
  username: aditya
  password: 
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: hackathon_test
  username: aditya
  password: 
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: hackathon_production
  pool: 5
  username: aditya
  password:
